"""
Tips Router — /api/tips/*

Language tips generated by Gemini. A random tip is served on every request
(no caching) so each login shows a different tip from the pool.

Endpoints:
  GET   /api/tips/random           — public, random tip on every call (no cache)
  POST  /api/tips/generate         — admin only, generate N tips via Gemini
  GET   /api/tips/all              — admin only, paginated + filterable list
  PATCH /api/tips/{tip_id}         — admin only, toggle is_active or update content
"""

import math
import uuid

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, Field
from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from backend.db.database import get_db
from backend.middleware.auth_middleware import get_current_user
from backend.models.tip import Tip
from backend.models.user import User
from backend.services.gemini_service import generate_json
from backend.utils.cache import cache_delete
from backend.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter()

# ── Category metadata ─────────────────────────────────────────────────────────

VALID_CATEGORIES = {"word_origin", "common_mistakes", "cultural_context", "grammar"}

_PROMPTS: dict[str, str] = {
    "word_origin": (
        "Generate {count} interesting facts about the origin or history of common "
        "Bahasa Melayu words. Each tip should be 1-2 sentences, engaging, and "
        "educational for international students at a Malaysian university. "
        "Return as JSON array of strings only."
    ),
    "common_mistakes": (
        "Generate {count} tips about common mistakes foreigners make when speaking "
        "Bahasa Melayu and how to avoid them. 1-2 sentences each. "
        "Return as JSON array of strings only."
    ),
    "cultural_context": (
        "Generate {count} tips about cultural context behind common Bahasa Melayu "
        "phrases or expressions. 1-2 sentences each. "
        "Return as JSON array of strings only."
    ),
    "grammar": (
        "Generate {count} quick Bahasa Melayu grammar tips understandable in "
        "1-2 sentences. Return as JSON array of strings only."
    ),
}


# ── Admin guard ───────────────────────────────────────────────────────────────


async def require_admin(current_user: User = Depends(get_current_user)) -> User:
    """Raise HTTP 403 for non-admin users."""
    if current_user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required",
        )
    return current_user


# ── Schemas ───────────────────────────────────────────────────────────────────


class TipResponse(BaseModel):
    id: str
    content: str
    category: str
    generated_by: str
    is_active: bool
    created_at: str

    model_config = {"from_attributes": True}


class TipListResponse(BaseModel):
    items: list[TipResponse]
    total: int
    page: int
    limit: int
    total_pages: int


class GenerateTipsRequest(BaseModel):
    category: str
    count: int = Field(default=5, ge=1, le=10)


class GenerateTipsResponse(BaseModel):
    saved: int
    category: str


class UpdateTipRequest(BaseModel):
    is_active: bool | None = None
    content: str | None = None


# ── Helpers ───────────────────────────────────────────────────────────────────


def _tip_to_response(tip: Tip) -> TipResponse:
    return TipResponse(
        id=str(tip.id),
        content=tip.content,
        category=tip.category,
        generated_by=tip.generated_by,
        is_active=tip.is_active,
        created_at=tip.created_at.isoformat(),
    )


# ── GET /api/tips/random ──────────────────────────────────────────────────────


@router.get("/random")
async def get_random_tip(
    db: AsyncSession = Depends(get_db),
) -> dict:
    """Return a random active tip on every call (no Redis cache).

    No caching ensures each login/page-load gets a different tip from the pool.
    No authentication required so the dashboard can call it before session loads.
    """
    try:
        result = await db.execute(
            select(Tip)
            .where(Tip.is_active == True)  # noqa: E712
            .order_by(func.random())
            .limit(1)
        )
        tip = result.scalar_one_or_none()

        if tip is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No tips available",
            )

        return _tip_to_response(tip).model_dump()

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Failed to fetch random tip", error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not fetch tip",
        )


# ── POST /api/tips/generate ───────────────────────────────────────────────────


@router.post("/generate", response_model=GenerateTipsResponse)
async def generate_tips(
    body: GenerateTipsRequest,
    _admin: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db),
) -> GenerateTipsResponse:
    """Generate N tips for a given category using Gemini and save to DB.

    Admin only. Count is capped at 10 per request. The daily_tip cache is
    cleared so a freshly generated tip can be served immediately.
    """
    if body.category not in VALID_CATEGORIES:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Invalid category. Must be one of: {', '.join(sorted(VALID_CATEGORIES))}",
        )

    prompt = _PROMPTS[body.category].format(count=body.count)

    try:
        raw = await generate_json(prompt)
    except Exception as exc:
        logger.error("Gemini tip generation failed", category=body.category, error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI generation failed — please try again",
        )

    # Expect a plain JSON array of strings
    if not isinstance(raw, list):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="AI returned unexpected format — expected a JSON array of strings",
        )

    saved = 0
    for item in raw:
        if not isinstance(item, str) or not item.strip():
            continue
        tip = Tip(
            content=item.strip(),
            category=body.category,
            generated_by="gemini",
            is_active=True,
        )
        db.add(tip)
        saved += 1

    if saved:
        await db.commit()
        # Invalidate daily cache so a new tip can surface
        await cache_delete("daily_tip")

    logger.info("Tips generated", category=body.category, saved=saved)
    return GenerateTipsResponse(saved=saved, category=body.category)


# ── GET /api/tips/all ─────────────────────────────────────────────────────────


@router.get("/all", response_model=TipListResponse)
async def list_all_tips(
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=20, ge=1, le=100),
    category: str | None = Query(default=None),
    is_active: bool | None = Query(default=None),
    _admin: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db),
) -> TipListResponse:
    """Paginated list of all tips — admin only.

    Filter by category and/or is_active status. Returns newest-first.
    """
    try:
        query = select(Tip)
        count_query = select(func.count()).select_from(Tip)

        if category:
            if category not in VALID_CATEGORIES:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=f"Invalid category",
                )
            query = query.where(Tip.category == category)
            count_query = count_query.where(Tip.category == category)

        if is_active is not None:
            query = query.where(Tip.is_active == is_active)
            count_query = count_query.where(Tip.is_active == is_active)

        total_result = await db.execute(count_query)
        total = total_result.scalar_one()

        offset = (page - 1) * limit
        result = await db.execute(
            query.order_by(Tip.created_at.desc()).offset(offset).limit(limit)
        )
        tips = result.scalars().all()

        return TipListResponse(
            items=[_tip_to_response(t) for t in tips],
            total=total,
            page=page,
            limit=limit,
            total_pages=max(1, math.ceil(total / limit)),
        )

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Failed to list tips", error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not fetch tips",
        )


# ── PATCH /api/tips/{tip_id} ──────────────────────────────────────────────────


@router.patch("/{tip_id}", response_model=TipResponse)
async def update_tip(
    tip_id: uuid.UUID,
    body: UpdateTipRequest,
    _admin: User = Depends(require_admin),
    db: AsyncSession = Depends(get_db),
) -> TipResponse:
    """Toggle is_active or update content for a tip — admin only.

    Invalidates the daily_tip Redis cache so changes are visible immediately.
    """
    try:
        result = await db.execute(select(Tip).where(Tip.id == tip_id))
        tip = result.scalar_one_or_none()

        if tip is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Tip not found",
            )

        if body.is_active is not None:
            tip.is_active = body.is_active
        if body.content is not None and body.content.strip():
            tip.content = body.content.strip()

        await db.commit()
        await db.refresh(tip)
        await cache_delete("daily_tip")

        logger.info("Tip updated", tip_id=str(tip_id))
        return _tip_to_response(tip)

    except HTTPException:
        raise
    except Exception as exc:
        logger.error("Failed to update tip", tip_id=str(tip_id), error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Could not update tip",
        )
