"""
Tip ORM Model

Table: tips
Stores AI-generated Bahasa Melayu learning tips served as a daily toast
notification. Tips are categorised and togglable by admins.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.db.database import Base


class Tip(Base):
    """A single language-learning tip generated by Gemini.

    Categories:
      'word_origin'       — etymology / history of a Malay word
      'common_mistakes'   — errors foreigners typically make
      'cultural_context'  — cultural background behind phrases
      'grammar'           — quick grammar rules
    """

    __tablename__ = "tips"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4,
        server_default=func.gen_random_uuid()
    )
    content: Mapped[str] = mapped_column(Text(), nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    generated_by: Mapped[str] = mapped_column(
        String(50), nullable=False, default="gemini", server_default="gemini"
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean(), nullable=False, default=True, server_default="true", index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    def __repr__(self) -> str:
        return f"<Tip category={self.category!r} active={self.is_active}>"
